version: 2

default: &default
  docker:
    - image: circleci/golang:1.17
  working_directory: /go/src/github.com/greymatter-io/operator

jobs:
  cibuild:
    <<: *default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./scripts/cibuild test
      - run: ./scripts/cibuild build
      - run: ./scripts/cibuild container
      - run: ./scripts/cibuild release

workflows:
  version: 2
  build-and-release:
    jobs:
      - cibuild:
          context: nexus
          # By default, Circle CI does not kick off a job on tags unless we specify
          # This workflow will run on every push and any tag push with a `v` prefix
          filters:
            tags:
              only: /^v.*/
