# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/gm-operator.clusterserviceversion.yaml
- ../../context/openshift
- ../samples
- ../scorecard
