apiVersion: apps/v1
kind: Deployment
metadata:
  name: gm-operator
  namespace: gm-operator
spec:
  template:
    spec:
      containers:
      - name: operator
        image: docker.greymatter.io/internal/gm-operator:latest
